---
name: Consistency and IPR Review (Add project title)
description: Enter the Issue title.
title: '[Consistency Review]: '
labels: [Consistency Review]
projects: [SCI AI Project]
assignees:
- Add Project lead details
body:
  - type: textarea
    id: Consistency-and-IPR-Review
    attributes:
      label: Company Submission
      description: Consistency Review
      placeholder: Consistency Review
      value: "Add your observations & comments here, along with the document section"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Add details"

